env: "local" 
storage_path: "./storage/booking.db"
tCheckerSeconds: 400
grpc: 
  addr: "0.0.0.0:45055"
  timeout: 5s
clients: 
  payments:
   address: "sport-box-payments:5055"
   timeout: 5s
   retriesCount: 3