env: "local"
AppSecret: "IloveDasha1205"
http_server:
  address: "0.0.0.0:8082"
  timeout: 5s
  idle_timeout: 60s
clients:
  sso:
   addr: "sport-box-sso:44044"
   timeout: 5s
   retriesCount: 3
  payments:
   addr: "sport-box-payments:45045"
   timeout: 5s
   retriesCount: 3
  booking:
   addr: "sport-box-booking:45055"
   timeout: 5s
   retriesCount: 3
   